name: Update GitHub Activity

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      # ✅ REQUIRED: Checkout the repository
      - uses: actions/checkout@v4

      # ✅ Update README with recent activity
      - uses: jamesgeorge007/github-activity-readme@v0.4.0
        with:
          GH_USERNAME: DennohDev
          COMMIT_NAME: github-actions[bot]
          COMMIT_EMAIL: 41898282+github-actions[bot]@users.noreply.github.com
          COMMIT_MSG: ":zap: Update README with the recent activity"
          MAX_LINES: 5
          TARGET_FILE: README.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

