name: GitHub Metrics

on:
  schedule:
    - cron: "0 0 * * *"   # runs daily
  workflow_dispatch:

jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          user: DennohDev
          token: ${{ secrets.GITHUB_TOKEN }}

          # Output
          filename: github-metrics.svg
          output_action: commit
          committer_message: "chore: update github metrics"

          # Base sections
          base: header, activity, community, repositories

          # Plugins
          plugin_languages: yes
          plugin_languages_limit: 8

          plugin_habits: yes
          plugin_habits_facts: yes
          plugin_habits_charts: yes

          plugin_streak: yes
          plugin_streak_days: yes

          plugin_activity: yes
          plugin_activity_limit: 5

          plugin_followup: yes
          plugin_followup_sections: repositories

          plugin_achievements: yes
          plugin_achievements_threshold: C

